apiVersion: v1
metadata:
  name: vault-config
  namespace: default
data:
  roleid: dF1nu8xT6jBz01iXAfYDCmGdQO1IOc4EOgqVB703
  secretid: root_token
  server: http://localhost:8300
kind: ConfigMap



# kubectl create -f  default-configmap.yml
#  kubectl get configmap vault-config -o yaml

kubectl create configmap vault-config --from-literal=server=http://localhost:8200 --from-literal=roleid=dF1nu8xT6jBz01iXAfYDCmGdQO1IOc4EOgqVB703 --from-literal=secretid=someid
