version: '3.4'

services:
 
  consoleapp:
    image: ${DOCKER_REGISTRY}consoleapp
    build:
      context: src/ConsoleApp/
      dockerfile: Dockerfile
    depends_on: 
     - vault

  webapp:
    image: ${DOCKER_REGISTRY}webapp
    build:
      context: src/WebApp/
      dockerfile: Dockerfile

  vault:
    image: vault:v0.6.0
    cap_add: 
     - IPC_LOCK
    environment:
     VAULT_ADDR: "http://127.0.0.1:8300"
     VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8300
     VAULT_DEV_ROOT_TOKEN_ID: root_dev_token
     VAULT_LOG: 'debug'
     SKIP_SETCAP: 'true'
    ports:
     - "8300:8300"
     - "8200:8200"
