version: '3.4'

services:
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44339
    ports:
      - "52767:80"
      - "44339:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  # vault:
  #   cap_add: 
  #    - IPC_LOCK
  #   environment:
  #    - VAULT_ADDR=http://127.0.0.1:8300
  #    - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8300
  #    - VAULT_DEV_ROOT_TOKEN_ID=root_dev_token
  #    - VAULT_LOG=debug
  #    - SKIP_SETCAP=true
  #   ports:
  #    - "8300:8300"
  #    - "8200:8200" 